# Generated by Django 5.1.2 on 2025-04-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geodetails',
            options={'verbose_name': 'Geo Details', 'verbose_name_plural': 'Geo Details'},
        ),
    ]
