# Generated by Django 5.1.2 on 2025-04-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('portal_admin', 'Portal Admin'), ('moderator', 'Moderator'), ('researcher', 'Researcher'), ('country_manager', 'Country Manager'), ('reporter', 'Reporter'), ('guest', 'Guest')], default='guest', max_length=255, unique=True),
        ),
    ]
