# Generated by Django 5.1.2 on 2025-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Super Admins', 'Super Admin'), ('Portal Admins', 'Portal Admin'), ('Moderators', 'Moderator'), ('Researchers', 'Researcher'), ('Country Managers', 'Country Manager'), ('Reporters', 'Reporter'), ('Guests', 'Guest')], default='Guests', max_length=255, unique=True),
        ),
    ]
