# Generated by Django 5.1.2 on 2025-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Portal Admin', 'Portal Admin'), ('Moderator', 'Moderator'), ('Researcher', 'Researcher'), ('Country Manager', 'Country Manager'), ('Reporter', 'Reporter'), ('Guest', 'Guest')], default='Guest', max_length=255, unique=True),
        ),
    ]
