# Generated by Django 5.1.2 on 2025-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_groups_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(auto_created=True, default='${first_name} ${last_name}', editable=False, max_length=255),
        ),
    ]
